---
abstract: 'Interface to Google Distance Matrix API.'
author:
  - 'Mohammad S Anwar <mohammad.anwar@yahoo.com>'
build_requires:
  HTTP::Request: 1.40
  LWP::UserAgent: 2.33
  Mouse: 0.93
  MouseX::Params::Validate: 0.01
  Readonly: 0
  Test::More: 0
  Test::Warn: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Google-DistanceMatrix
provides:
  WWW::Google::DistanceMatrix:
    file: lib/WWW/Google/DistanceMatrix.pm
    version: 0.01
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
